"""Adiciona unicidade para sigla em pessoa juridica

Revision ID: 2e0bc0743baf
Revises: c17976e082fb
Create Date: 2026-02-14 17:20:01.180078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0bc0743baf'
down_revision: Union[str, None] = 'c17976e082fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pessoas_juridicas_id', table_name='pessoas_juridicas')
    op.drop_table('pessoas_juridicas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas_juridicas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('razao_social', sa.VARCHAR(), nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(), nullable=True),
    sa.Column('sigla', sa.VARCHAR(length=3), nullable=False),
    sa.Column('tipo', sa.VARCHAR(), nullable=True),
    sa.Column('cnpj', sa.VARCHAR(), nullable=False),
    sa.Column('inscricao_estadual', sa.VARCHAR(), nullable=True),
    sa.Column('inscricao_municipal', sa.VARCHAR(), nullable=True),
    sa.Column('endereco', sa.VARCHAR(), nullable=True),
    sa.Column('complemento', sa.VARCHAR(), nullable=True),
    sa.Column('cidade', sa.VARCHAR(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.Column('cep', sa.VARCHAR(), nullable=True),
    sa.Column('pais', sa.VARCHAR(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index('ix_pessoas_juridicas_id', 'pessoas_juridicas', ['id'], unique=False)
    # ### end Alembic commands ###
