"""Adiciona unicidade para sigla em pessoa juridica

Revision ID: 2e0bc0743baf
Revises: c17976e082fb
Create Date: 2026-02-14 17:20:01.180078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0bc0743baf'
down_revision: Union[str, None] = 'c17976e082fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona coluna tipo e torna sigla unique
    op.add_column('pessoas_juridicas', sa.Column('tipo', sa.VARCHAR(), nullable=True))
    op.alter_column('pessoas_juridicas', 'sigla', type_=sa.VARCHAR(length=3), nullable=False)
    op.create_unique_constraint('uq_pessoas_juridicas_sigla', 'pessoas_juridicas', ['sigla'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pessoas_juridicas_sigla', 'pessoas_juridicas', type_='unique')
    op.alter_column('pessoas_juridicas', 'sigla', type_=sa.VARCHAR(), nullable=True)
    op.drop_column('pessoas_juridicas', 'tipo')
    # ### end Alembic commands ###
