"""Nova migração do banco de dados

Revision ID: ec7c8b65777b
Revises: d3292e596a53
Create Date: 2026-02-16 22:47:03.673407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7c8b65777b'
down_revision: Union[str, None] = 'd3292e596a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=True),
    sa.Column('telefone_fixo', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_table('pessoas_juridicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(length=3), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('inscricao_estadual', sa.String(), nullable=True),
    sa.Column('inscricao_municipal', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_pessoas_juridicas_id'), 'pessoas_juridicas', ['id'], unique=False)
    op.create_table('produtos_servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=8), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUTO', 'SERVICO', name='tipoprodutoservico'), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('codigo_fabricante', sa.String(length=50), nullable=True),
    sa.Column('nome_fabricante', sa.String(length=255), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ncm_lcp', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_servicos_codigo_interno'), 'produtos_servicos', ['codigo_interno'], unique=True)
    op.create_index(op.f('ix_produtos_servicos_id'), 'produtos_servicos', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_juridica_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=True),
    sa.Column('telefone_fixo', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_juridica_id'], ['pessoas_juridicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_id'), 'contatos', ['id'], unique=False)
    op.create_table('produtos_servicos_fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_servico_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=50), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('icms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['pessoas_juridicas.id'], ),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['produtos_servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_servicos_fornecedores_id'), 'produtos_servicos_fornecedores', ['id'], unique=False)
    op.create_table('produtos_servicos_historico_precos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_servico_id', sa.Integer(), nullable=False),
    sa.Column('preco_medio', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('preco_minimo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('preco_maximo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['produtos_servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_servicos_historico_precos_id'), 'produtos_servicos_historico_precos', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('tecnico', sa.String(length=255), nullable=False),
    sa.Column('valor_orcado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_venda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('data_pedido_compra', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ORCANDO', 'ORCAMENTO_ENVIADO', 'DECLINADO', 'EM_EXECUCAO', 'AGUARDANDO_PEDIDO', 'TESTE_VIABILIDADE', 'CONCLUIDO', name='statusprojeto'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['pessoas_juridicas.id'], ),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_index(op.f('ix_projetos_numero'), 'projetos', ['numero'], unique=True)
    op.create_table('cronogramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('percentual_conclusao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id')
    )
    op.create_index(op.f('ix_cronogramas_id'), 'cronogramas', ['id'], unique=False)
    op.create_table('despesas_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_despesa', sa.String(length=50), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_responsavel_id', sa.Integer(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'ENVIADO', 'CONFIRMADO', 'PARCIALMENTE_ENTREGUE', 'ENTREGUE', 'CANCELADO', name='statusdespesa'), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('previsao_entrega', sa.Date(), nullable=True),
    sa.Column('prazo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('condicao_pagamento', sa.String(length=100), nullable=True),
    sa.Column('tipo_frete', sa.Enum('CIF', 'FOB', name='tipofrete'), nullable=True),
    sa.Column('valor_frete', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['pessoas_juridicas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_responsavel_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_projetos_id'), 'despesas_projetos', ['id'], unique=False)
    op.create_index(op.f('ix_despesas_projetos_numero_despesa'), 'despesas_projetos', ['numero_despesa'], unique=True)
    op.create_table('faturamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('valor_faturado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_faturamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faturamentos_id'), 'faturamentos', ['id'], unique=False)
    op.create_table('cronogramas_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cronograma_id', sa.Integer(), nullable=False),
    sa.Column('percentual_conclusao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cronograma_id'], ['cronogramas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronogramas_historico_id'), 'cronogramas_historico', ['id'], unique=False)
    op.create_table('despesas_projetos_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('despesa_projeto_id', sa.Integer(), nullable=False),
    sa.Column('produto_servico_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('icms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ipi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['despesa_projeto_id'], ['despesas_projetos.id'], ),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['produtos_servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_projetos_itens_id'), 'despesas_projetos_itens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_despesas_projetos_itens_id'), table_name='despesas_projetos_itens')
    op.drop_table('despesas_projetos_itens')
    op.drop_index(op.f('ix_cronogramas_historico_id'), table_name='cronogramas_historico')
    op.drop_table('cronogramas_historico')
    op.drop_index(op.f('ix_faturamentos_id'), table_name='faturamentos')
    op.drop_table('faturamentos')
    op.drop_index(op.f('ix_despesas_projetos_numero_despesa'), table_name='despesas_projetos')
    op.drop_index(op.f('ix_despesas_projetos_id'), table_name='despesas_projetos')
    op.drop_table('despesas_projetos')
    op.drop_index(op.f('ix_cronogramas_id'), table_name='cronogramas')
    op.drop_table('cronogramas')
    op.drop_index(op.f('ix_projetos_numero'), table_name='projetos')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_produtos_servicos_historico_precos_id'), table_name='produtos_servicos_historico_precos')
    op.drop_table('produtos_servicos_historico_precos')
    op.drop_index(op.f('ix_produtos_servicos_fornecedores_id'), table_name='produtos_servicos_fornecedores')
    op.drop_table('produtos_servicos_fornecedores')
    op.drop_index(op.f('ix_contatos_id'), table_name='contatos')
    op.drop_table('contatos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_produtos_servicos_id'), table_name='produtos_servicos')
    op.drop_index(op.f('ix_produtos_servicos_codigo_interno'), table_name='produtos_servicos')
    op.drop_table('produtos_servicos')
    op.drop_index(op.f('ix_pessoas_juridicas_id'), table_name='pessoas_juridicas')
    op.drop_table('pessoas_juridicas')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
