"""Adiciona tabela de contatos

Revision ID: efda0c94b422
Revises: 2e0bc0743baf
Create Date: 2026-02-14 17:52:24.416112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efda0c94b422'
down_revision: Union[str, None] = '2e0bc0743baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contatos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pessoa_juridica_id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('departamento', sa.VARCHAR(), nullable=True),
    sa.Column('telefone_fixo', sa.VARCHAR(), nullable=True),
    sa.Column('celular', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_juridica_id'], ['pessoas_juridicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contatos_id', 'contatos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contatos_id', table_name='contatos')
    op.drop_table('contatos')
    # ### end Alembic commands ###
